spring:
  application:
    name: xbook
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost/xbook?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: 123456789
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://ec2-34-194-158-176.compute-1.amazonaws.com:5432/d8mbr94t010d6b
#    username: nfgnzdnefakzkv
#    password: 05565ba05b2bc6f344f1dc8d9a3f2a343748cdc26d1d4d58a928316ed4b2b273
#  data:
#    cassandra:
#      schema-action: create_if_not_exists
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${XBOOK_SERVER_PORT:9999}
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

jwt:
  secret: 540E772F66BCAF43C9BE3E3DA90F31BBA8C738884C9B3AAF7CE4FED15DCFC7E7
  expirationDateInMs: 18000000

cloudinary:
  cloud_name: ahihi
  api_key: 268736226145353
  api_secret: BODd_eO3cqqHh0p4KPdS0GH0HPU

application:
  version: ${VERSION:1.0}
  swagger:
#    base-uri: localhost
    base-uri: https://xbook-ados.herokuapp.com/

user:
  username: admin
  password: admin
  gender: 0
  fullname: ADMIN
  address: Hanoi
  phone: 0123456789

